---
title: "Combine model results"
project:
  output-dir: outputs
date: last-modified
format: 
  html:
    page-layout: full
toc: true
editor: visual
warning: false
execute: 
  freeze: true
  warning: false
---

# Environment Setup

```{r setup}
# Packages
library(tidyverse)

# Folder Structure
root <- rprojroot::has_file("extreme-heat-vs-sv.Rproj")$make_fix_file()
proc_data_dir <- root("data/processed")
fig_dir <- root("figures")
```

# Notebook settings

```{r}
# Viz settings
col_palette <- c("#dc7726", "#eebb93", "#ecc046", "#f6e0a3", "#0292b7", "#81c9db", "#35A29F", "#97DECE")
```

# Load data

```{r}
df_heat_np <- read_csv(file.path(proc_data_dir, "heat_effect_stats_excess_hot_days_np_viol.csv"), show_col_types = FALSE)
df_heat_ip <- read_csv(file.path(proc_data_dir, "heat_effect_stats_excess_hot_days_ip_viol.csv"), show_col_types = FALSE)
df_heat_rel <- read_csv(file.path(proc_data_dir, "heat_effect_stats_excess_hot_days_rel_viol.csv"), show_col_types = FALSE)
df_heat_nrel <- read_csv(file.path(proc_data_dir, "heat_effect_stats_excess_hot_days_nrel_viol.csv"), show_col_types = FALSE)
```

# Combine

```{r}
df_heat <- (
  bind_rows(
    df_heat_np, 
    df_heat_ip,
    df_heat_rel,
    df_heat_nrel
  )
  %>% mutate(
    model = factor(model, levels = c("Spatial correlation", "Random slopes", "Base model"))
  )
)
```

# Viz

```{r}
#| fig-width: 6.5
#| fig-height: 3

dodge <- ggstance::position_dodgev(height = 0.8)

lims <- c(
  min(df_heat$lower2_val, 0.95), 
  max(df_heat$upper2_val)
)

(
  df_heat
  %>% ggplot(
    mapping = aes(
      y = fct_reorder(outcome, median_val),
      color = model
    )
  )
  + geom_segment(
    mapping = aes(
      x = lower2_val,
      xend = upper2_val
    ),
    position = dodge,
    linewidth = 1
  )
  + geom_segment(
    mapping = aes(
      x = lower1_val,
      xend = upper1_val
    ),
    position = dodge,
    linewidth = 2
  )
  + geom_point(
    mapping = aes(
      x = median_val,
    ),
    size = 3,
    position = dodge
  )
  + geom_vline(
    xintercept = 1,
    linetype = "dashed",
    color = "black"
  )
  + scale_color_manual(
    breaks = c("Base model", "Random slopes", "Spatial correlation"),
    values = c(
      "Base model" = col_palette[1],
      "Random slopes" = col_palette[3],
      "Spatial correlation" = col_palette[5]
    )
  )
  + scale_x_continuous(
    limits = lims
  )
  + theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_rect(fill = NA, color = "black", linewidth = 1),
    plot.background = element_blank(),
    plot.title = element_text(size = 14, hjust = 0.5),
    plot.subtitle = element_text(size = 13, hjust = 0.5),,
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 13),
    legend.background = element_blank(),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 13),
    legend.position = "inside",
    legend.position.inside = c(0.8, 0.25)
  )
  + labs(
    x = "Population Level Heat Risk Odds Ratio",
    y = "Perpetrator",
    color = "Model"
  )
)

ggsave(
  path = fig_dir,
  filename = "model_summary.png"
)
```

